services:
  # WordPress Backend (sin MySQL local)
  wordpress:
    image: wordpress:latest
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: ${EXTERNAL_DB_HOST}
      WORDPRESS_DB_USER: ${EXTERNAL_DB_USER}
      WORDPRESS_DB_PASSWORD: ${EXTERNAL_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${EXTERNAL_DB_NAME}
      WORDPRESS_DEBUG: 1
      WORDPRESS_HOME_URL: ${WORDPRESS_HOME_URL}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
    volumes:
      - wordpress_data:/var/www/html
      - ./backend/uploads:/var/www/html/wp-content/uploads
    networks:
      - atm_network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_WORDPRESS_API_URL=${REACT_APP_WORDPRESS_API_URL}
      - REACT_APP_ENV=development
    env_file:
      - ./frontend/.env.development.docker
    depends_on:
      - wordpress
    networks:
      - atm_network
    restart: unless-stopped

  # Nginx para producción
  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - wordpress
    networks:
      - atm_network
    restart: unless-stopped

networks:
  atm_network:
    driver: bridge

volumes:
  wordpress_data: 