name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug VPS_HOST and VPS_PORT
        run: |
          echo "VPS_HOST = '${{ secrets.VPS_HOST }}'"
          echo "VPS_PORT = '${{ secrets.VPS_PORT }}'"

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 5137 -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: |
          ssh -p 5137 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/atmweb || exit 1
            git pull origin main
            docker compose down
            docker compose up -d --build --pull always
          EOF
